default-world: world

timing:
  delay: 5
  cool-down: 150
  time-out: 30

message:
  request:
    already-sent: "§cYou have already sent request to <to>"
    sent: "§eYour request to <to> is sent"
    got: "§eYou have recieved request from <from>"
    you-have-no: "§cYou have no requests"
    you-have-no-from: "§cYou have no request from <from>"
    you-have-denied: "§eYou have denied request from <from>"
    your-was-denied: "§cYour request to <to> was denied"
    you-have-accepted: "§aYou have accepted request from <from>"
    your-was-accepted: "§aYour request to <to> was accepted"
    your-time-out: "§cYour request's to <to> time out"
    time-out: "§eRequest's from <from> time out"
    list-header: "Your requests (<count>):"
    list-item: "- <from>"
    specify: "§cYou have <count> requests. Please specify player's name whose request you want to answer to"

  teleport:
    cannot: "§c<from> cannot be teleported now"
    to-location: "Teleporting"
    to-named-location: "Teleporting to <to>"
    to-player: "Teleporting to <to> in"
    to-you: "<from> is teleporting to you in"
    count-down: "<left-seconds>"
    finish: "§aTeleported"
    seconds: "second(s)"

  error:
    cannot-send-request-to-your-self: "§cYou cannot send request to your self"
    wait-until-cool-down-over: "§cWait until your cool down is over.\n<left> remaining"
    missing-bed: "§cYour bed isn't available now" 
    already-teleporting: "§cYou are already teleporting"
