name: CPSpeed
version: "${project.version}"
description: Provides teleportation commands
author: maksim2498

main: space.moontalk.mc.cpspeed.CPSpeed
api-version: 1.13

commands:
  tpa:
    description: Teleports you to specified player
    permission: cpspeed.tpa
    usage: |
      /<command> list sent
      /<command> list got
      /<command> [to] <player name>
      /<command> accept [<player name>]
      /<command> deny [<player name>]

  warp:
    description: Teleports you to specified warp
    permission: cpspeed.warp
    usage: |
      /<command> list [all]
      /<command> list global
      /<command> list my 
      /<command> list <player name>

      /<command> [to] [global] <warp name>
      /<command> [to] my <warp name>
      /<command> [to] <warp name> <player name>

      /<command> set global [<warp name>]
      /<command> set [my] <warp name>
      /<command> set [<warp name>] [<player name>]

      /<command> (remove | rm) global <warp name>
      /<command> (remove | rm) [my] <warp name>
      /<command> (remove | rm) <warp name> <player name>

      /<command> rename global <warp name>
      /<command> rename [my] <warp name>
      /<command> rename <warp name> <player name>

  spawn:
    description: Teleports you to your spawn
    permission: cpspeed.spawn
    usage: /<command> 

  worldspawn:
    description: Teleports you to worldspawn
    permission: cpspeed.worldspawn
    usage: /<command> [<world name>]
    aliases: [wspawn]

permissions:
  cpspeed.tpa:
    description: Allowed players to use tpa command
    default: true

  cpspeed.tpa.list.got.self:
    description: Allowes players to list got requests
    default: true

  cpspeed.tpa.list.got.other:
    description: Allowes players to list other players' got requests
    default: op

  cpspeed.tpa.list.sent.self:
    description: Allowes players to list sent requests
    default: true

  cpspeed.tpa.list.sent.other:
    description: Allowes players to list other players' sent requests
    default: op

  cpspeed.tpa.to:
    description: Allowes players to teleport to each other
    default: true

  cpspeed.tpa.accept:
    description: Allowes players to accept teleportation requests
    default: true

  cpspeed.tpa.deny:
    description: Allowes players to deny teleportation requests
    default: true

  cpspeed.spawn:
    description: Allowes players to teleport to their spawn
    default: true

  cpspeed.worldspawn:
    description: Allowes players to teleport to world spawn
    default: true
