name: CPSpeed
version: "${project.version}"
description: Provides teleportation commands
author: maksim2498

main: space.moontalk.mc.cpspeed.CPSpeed
api-version: 1.13

commands:
  tpa:
    description: Teleports you to specified player
    permission: cpspeed.tpa
    usage: |
      /<command> list sent
      /<command> list got
      /<command> [to] <player name>
      /<command> accept [<player name>]
      /<command> deny [<player name>]

  warp:
    description: Teleports you to specified warp
    permission: cpspeed.warp
    usage: |
      /<command> list [all]
      /<command> list global
      /<command> list my 
      /<command> list <player name>

      /<command> [to] [global] <warp name>
      /<command> [to] my <warp name>
      /<command> [to] <warp name> <player name>

      /<command> set global [<warp name>]
      /<command> set [my] <warp name>
      /<command> set [<warp name>] [<player name>]

      /<command> (remove | rm) global <warp name>
      /<command> (remove | rm) [my] <warp name>
      /<command> (remove | rm) <warp name> <player name>

      /<command> rename global <old warp name> <new warp name>
      /<command> rename [my] <old warp name> <new warp name>
      /<command> rename <old warp name> <new warp name> <player name>

  spawn:
    description: Teleports you to your spawn
    permission: cpspeed.spawn
    usage: /<command> [<player name>]

  worldspawn:
    description: Teleports you to worldspawn
    permission: cpspeed.worldspawn
    usage: /<command> [<world name>]
    aliases: [wspawn]

permissions:
  # Tpa:

  cpspeed.tpa:
    description: Allowed usage of tpa command
    default: true

  # - List:

  cpspeed.tpa.list.got.self:
    description: Allowes to list got requests
    default: true

  cpspeed.tpa.list.got.other:
    description: Allowes to list other players' got requests
    default: op

  cpspeed.tpa.list.sent.self:
    description: Allowes to list sent requests
    default: true

  cpspeed.tpa.list.sent.other:
    description: Allowes to list other players' sent requests
    default: op

  # - To:
  
  cpspeed.tpa.to:
    description: Allowes to teleport to each other
    default: true

  # - Accept:

  cpspeed.tpa.accept:
    description: Allowes to accept teleportation requests
    default: true

  # - Deny:

  cpspeed.tpa.deny:
    description: Allowes to deny teleportation requests
    default: true



  # Warp:

  cpspeed.warp:
    description: Allowes usage of warp commands
    default: true

  # - List:

  cpspeed.warp.list.all:
    description: Allowes to list all warps
    default: true

  cpspeed.warp.list.global:
    description: Allowes to list global warps
    default: true

  cpspeed.warp.list.self:
    description: Allowes to list personal warps
    default: true

  cpspeed.warp.list.other:
    description: Allowes to list other players' warps
    default: op

  # - To:

  cpspeed.warp.to.global:
    description: Allowes to teleport to global warps
    default: true

  cpspeed.warp.to.self:
    description: Allowes to teleport to personal warps
    default: true

  cpspeed.warp.to.other:
    description: Allowes to teleport to other players' warps
    default: op

  # - Set:

  cpspeed.warp.set.global:
    description: Allowes to set global warps
    default: op

  cpspeed.warp.set.self:
    description: Allowes to set personal warps
    default: true

  cpspeed.warp.set.other:
    description: Allowes to set other players' warps
    default: op

  # - Remove:

  cpspeed.warp.remove.global:
    description: Allowes to remove global warps
    default: op

  cpspeed.warp.remove.self:
    description: Allowes to remove personal warps
    default: true

  cpspeed.warp.remove.other:
    description: Allowes to remove other players' warps
    default: op

  # - Rename:

  cpspeed.warp.rename.global:
    description: Allowes to rename global warps
    default: op

  cpspeed.warp.rename.self:
    description: Allowes to rename personal warps
    default: true

  cpspeed.warp.rename.other:
    description: Allowes to rename other players' warps
    default: op



  # Spawn:

  cpspeed.spawn:
    description: Allowes usage of spawn commands
    default: true

  cpspeed.spawn.self:
    description: Allowes to teleport to your own spawn
    default: true

  cpspeed.spawn.other:
    description: Allowes to teleport to other players' spawn
    default: op



  # World Spawn:

  cpspeed.worldspawn:
    description: Allowes to teleport to world spawn
    default: true
